{{- if .Values.flower.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "nh-data-ingestion.flower.fullname" . }}
  labels:
    {{- include "nh-data-ingestion.flower.labels" . | nindent 4 }}
spec:
  type: {{ .Values.flower.service.type }}
  ports:
    - port: {{ .Values.flower.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "nh-data-ingestion.flower.selectorLabels" . | nindent 4 }}
{{- end }}
