{{- if .Values.flower.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nh-data-ingestion.flower.fullname" . }}
  labels:
    {{- include "nh-data-ingestion.flower.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.flower.replicaCount }}
  selector:
    matchLabels:
      {{- include "nh-data-ingestion.flower.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.flower.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "nh-data-ingestion.flower.labels" . | nindent 8 }}
        {{- with .Values.flower.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "nh-data-ingestion.serviceAccountName" . }}
      {{- with .Values.flower.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: flower
          {{- with .Values.flower.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.flower.image.repository }}:{{ .Values.flower.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.flower.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.flower.service.targetPort }}
              protocol: TCP
          {{- with .Values.flower.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.flower.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.flower.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.flower.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            - name: REDIS_URL
              value: {{ .Values.config.redisUrl | quote }}
            {{- if .Values.flower.extraEnvVars }}
            {{- toYaml .Values.flower.extraEnvVars | nindent 12 }}
            {{- end }}
          envFrom:
            {{- include "nh-data-ingestion.commonEnvFrom" . | nindent 12 }}
      {{- with .Values.flower.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.flower.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.flower.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.flower.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
