{{- if .Values.scheduler.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nh-data-ingestion.scheduler.fullname" . }}
  labels:
    {{- include "nh-data-ingestion.scheduler.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.scheduler.replicaCount }}
  selector:
    matchLabels:
      {{- include "nh-data-ingestion.scheduler.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.scheduler.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "nh-data-ingestion.scheduler.labels" . | nindent 8 }}
        {{- with .Values.scheduler.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "nh-data-ingestion.serviceAccountName" . }}
      {{- with .Values.scheduler.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: scheduler
          {{- with .Values.scheduler.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.scheduler.image.repository }}:{{ .Values.scheduler.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.scheduler.image.pullPolicy }}
          {{- with .Values.scheduler.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.scheduler.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.scheduler.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.scheduler.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            {{- include "nh-data-ingestion.commonEnv" . | nindent 12 }}
            - name: CELERY_LOGLEVEL
              value: {{ .Values.scheduler.celery.loglevel | quote }}
            {{- if .Values.scheduler.extraEnvVars }}
            {{- toYaml .Values.scheduler.extraEnvVars | nindent 12 }}
            {{- end }}
          envFrom:
            {{- include "nh-data-ingestion.commonEnvFrom" . | nindent 12 }}
      {{- with .Values.scheduler.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.scheduler.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.scheduler.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.scheduler.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
