{{- if .Values.worker.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "nh-rag.fullname" . }}-worker
  labels:
    {{- include "nh-rag.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  type: {{ .Values.worker.service.type }}
  ports:
    - port: {{ .Values.worker.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "nh-rag.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: worker
{{- end }}

